In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("forestfires.csv")

In [3]:
df

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4   sep  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4   aug  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4   aug  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4   sep  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3   sep  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4   aug  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4   aug  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4   aug  wed  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4   aug  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4   aug  thu  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6   aug  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6   aug  mon  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5   aug  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4   aug  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4   aug  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4   aug  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9 

In [4]:
df.drop(["month"], axis=1, inplace=True)
df.drop(["day"], axis=1, inplace=True)

In [5]:
df

X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3  79.5    3.0  106.7   1.1  11.

In [6]:
df.corr()

X         Y      FFMC       DMC        DC       ISI      temp  \
X     1.000000  0.539548 -0.021039 -0.048384 -0.085916  0.006210 -0.051258   
Y     0.539548  1.000000 -0.046308  0.007782 -0.101178 -0.024488 -0.024103   
FFMC -0.021039 -0.046308  1.000000  0.382619  0.330512  0.531805  0.431532   
DMC  -0.048384  0.007782  0.382619  1.000000  0.682192  0.305128  0.469594   
DC   -0.085916 -0.101178  0.330512  0.682192  1.000000  0.229154  0.496208   
ISI   0.006210 -0.024488  0.531805  0.305128  0.229154  1.000000  0.394287   
temp -0.051258 -0.024103  0.431532  0.469594  0.496208  0.394287  1.000000   
RH    0.085223  0.062221 -0.300995  0.073795 -0.039192 -0.132517 -0.527390   
wind  0.018798 -0.020341 -0.028485 -0.105342 -0.203466  0.106826 -0.227116   
rain  0.065387  0.033234  0.056702  0.074790  0.035861  0.067668  0.069491   
area  0.063385  0.044873  0.040122  0.072994  0.049383  0.008258  0.097844   

            RH      wind      rain      area  
X     0.085223  0.018798  0.065387  0.063385  
Y     0.062221 -0.020341  0.033234  0.044873  
FFMC -0.300995 -0.028485  0.056702  0.040122  
DMC   0.073795 -0.105342  0.074790  0.072994  
DC   -0.039192 -0.203466  0.035861  0.049383  
ISI  -0.132517  0.106826  0.067668  0.008258  
temp -0.527390 -0.227116  0.069491  0.097844  
RH    1.000000  0.069410  0.099751 -0.075519  
wind  0.069410  1.000000  0.061119  0.012317  
rain  0.099751  0.061119  1.000000 -0.007366  
area -0.075519  0.012317 -0.007366  1.000000

In [7]:
x=df[["X","Y","FFMC","DMC","DC","ISI","temp","RH","wind","rain"]]
x.dtypes

X         int64
Y         int64
FFMC    float64
DMC     float64
DC      float64
ISI     float64
temp    float64
RH        int64
wind    float64
rain    float64
dtype: object

In [8]:
y=df["area"]

In [9]:
from sklearn import preprocessing

In [10]:
import statsmodels.api as sm
model=sm.OLS(y, x).fit()
prediction = model.predict(x)
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   area   R-squared:                       0.060
Model:                            OLS   Adj. R-squared:                  0.041
Method:                 Least Squares   F-statistic:                     3.235
Date:                Wed, 19 Jun 2019   Prob (F-statistic):           0.000465
Time:                        10:38:16   Log-Likelihood:                -2874.8
No. Observations:                 517   AIC:                             5770.
Df Residuals:                     507   BIC:                             5812.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X              1.9135      1.446      1.323      0.186      -0.927       4.754
Y              0.5225      2.695      0.194      0.846      -4.771       5.816
FFMC          -0.1012      0.246     -0.411      0.681      -0.585       0.383
DMC            0.0794      0.064      1.242      0.215      -0.046       0.205
DC            -0.0033      0.016     -0.200      0.842      -0.036       0.029
ISI           -0.6819      0.703     -0.969      0.333      -2.064       0.700
temp           0.7774      0.754      1.032      0.303      -0.703       2.258
RH            -0.2425      0.206     -1.178      0.240      -0.647       0.162
wind           1.5245      1.636      0.932      0.352      -1.690       4.739
rain          -3.2963      9.613     -0.343      0.732     -22.182      15.589
==============================================================================
Omnibus:                      975.107   Durbin-Watson:                   1.647
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           781550.358
Skew:                          12.571   Prob(JB):                         0.00
Kurtosis:                     191.809   Cond. No.                     2.14e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.14e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [11]:
x = preprocessing.StandardScaler().fit(x).transform(x.astype("float"))  
x

C:\Users\danie\anaconda\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


array([[ 1.00831277,  0.56986043, -0.80595947, ...,  0.41172435,
         1.49861442, -0.07326831],
       [ 1.00831277, -0.24400101, -0.00810203, ..., -0.69245628,
        -1.74175564, -0.07326831],
       [ 1.00831277, -0.24400101, -0.00810203, ..., -0.69245628,
        -1.51828184, -0.07326831],
       ...,
       [ 1.00831277, -0.24400101, -1.64008316, ...,  1.57724834,
         1.49861442, -0.07326831],
       [-1.58736044, -0.24400101,  0.68095666, ..., -0.14036597,
        -0.00983371, -0.07326831],
       [ 0.57570057, -1.05786246, -2.02087875, ..., -0.81514302,
         0.26950853, -0.07326831]])

In [12]:
x

array([[ 1.00831277,  0.56986043, -0.80595947, ...,  0.41172435,
         1.49861442, -0.07326831],
       [ 1.00831277, -0.24400101, -0.00810203, ..., -0.69245628,
        -1.74175564, -0.07326831],
       [ 1.00831277, -0.24400101, -0.00810203, ..., -0.69245628,
        -1.51828184, -0.07326831],
       ...,
       [ 1.00831277, -0.24400101, -1.64008316, ...,  1.57724834,
         1.49861442, -0.07326831],
       [-1.58736044, -0.24400101,  0.68095666, ..., -0.14036597,
        -0.00983371, -0.07326831],
       [ 0.57570057, -1.05786246, -2.02087875, ..., -0.81514302,
         0.26950853, -0.07326831]])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.4)

In [15]:
y_train.shape

(310,)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lr = LinearRegression()

In [18]:
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
y_pred=lr.predict(x_test)

In [20]:
y_pred

array([ 28.7617208 ,   6.92796744,  10.40283779,   3.73515988,
        22.81785644,  10.59962957,  17.86707896,  48.61899282,
        12.80447969,   6.77814595,   3.74322808,   2.76300531,
        15.29494103,  33.86380493,  28.12466309,  30.6707248 ,
         7.13860528,  12.49941452,  12.87131183,  -2.49643719,
        21.34682606,  25.35698827,   8.08603704,  16.8282506 ,
        23.22673717,  42.98251387, -23.38399276,  11.15312514,
        -3.03951906,   2.1932127 ,  23.37752493,   4.84318759,
        22.79459058,  31.87829518,  18.66289866,   0.67150208,
        16.77281441,  17.21068951,  -8.49573486,  21.81332715,
        20.4034153 ,  17.94328768,   7.45416373,  23.55975872,
        -7.4095782 ,  17.52111367,  21.91489936,  19.46204249,
        -3.79798701,   7.97486846,  19.42109159,  17.57880493,
        12.18505851,  25.64036865,   9.91359703,  10.32055816,
        19.12833886,  19.50851633,  24.4333186 ,   6.23513827,
         8.81317175,   3.91461905,  13.54639911,  -8.71

In [21]:
y_pred.reshape(1,-1)

array([[ 28.7617208 ,   6.92796744,  10.40283779,   3.73515988,
         22.81785644,  10.59962957,  17.86707896,  48.61899282,
         12.80447969,   6.77814595,   3.74322808,   2.76300531,
         15.29494103,  33.86380493,  28.12466309,  30.6707248 ,
          7.13860528,  12.49941452,  12.87131183,  -2.49643719,
         21.34682606,  25.35698827,   8.08603704,  16.8282506 ,
         23.22673717,  42.98251387, -23.38399276,  11.15312514,
         -3.03951906,   2.1932127 ,  23.37752493,   4.84318759,
         22.79459058,  31.87829518,  18.66289866,   0.67150208,
         16.77281441,  17.21068951,  -8.49573486,  21.81332715,
         20.4034153 ,  17.94328768,   7.45416373,  23.55975872,
         -7.4095782 ,  17.52111367,  21.91489936,  19.46204249,
         -3.79798701,   7.97486846,  19.42109159,  17.57880493,
         12.18505851,  25.64036865,   9.91359703,  10.32055816,
         19.12833886,  19.50851633,  24.4333186 ,   6.23513827,
          8.81317175,   3.91461905,  13.

In [22]:
from sklearn.metrics import r2_score

In [23]:
r2_score(y_test, y_pred)#test accuracy

-0.15635099143282805

In [25]:
y_test = y_test.values.reshape(-1,1)

In [26]:
lr.score(y_test, y_pred)

ValueError: shapes (207,1) and (10,) not aligned: 1 (dim 1) != 10 (dim 0)

In [27]:
r2_score(y_train, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [310, 207]

In [ ]:
x_l = df["temp"]

In [ ]:
y = df["area"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.45)

In [ ]:
lm = LinearRegression()

In [ ]:
lm.fit(x_train, y_train)

In [ ]:
y_pred = lm.predict(x_test)

In [ ]:
y_pred

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test, y_pred)

In [ ]:
lm.score(x_train, y_train)

In [ ]:
lm.score(x_test, y_test)